### PR TITLE
Footer Design Added

### PR DESCRIPTION
**Pull request by sid172014**

### CODE REVIEW

**Comment by isyneha** [comment]
Wow, Great Job @sid172014 ! Just remove Dr from the Name in the footer section. This looks good to me. What say @aastha-chauhan-gits ?

**Review by isyneha — APPROVED** [review]

**Review by aastha-chauhan-gits — CHANGES_REQUESTED** [review]
Please Sync your code before any changes and I suggest you to remove 'paragraph', 'Dr.' and the whole 'useful links section' from footer section. And please add proper comments so that everyone can understand and fill their info easily.

**Comment by sid172014** [comment]
Aight , I'm on it

**Comment by sid172014** [comment]
Hey there , @aastha-chauhan-gits i've made your proposed changes , can you please have a look..

**Comment by sid172014** [comment]
Here's how the footer looks now

Screenshot 2022-10-10 at 2 07 48 PM

**Review by aastha-chauhan-gits — CHANGES_REQUESTED** [review]
Hey! Please First "Sync" the repo and then make new changes. Also Address and contact no. are enough in footer section, so remove the 'Subscribe to my NewsLetter' section. And from the social media section remove the 'G+' and 'Twitter' icons and add 'Instagram' instead. 
We have improved code of index.html so first sync the code.

**Comment by sid172014** [comment]
Sorry for the inconvenience I'll make a new PR

**Pull request closed without merging**
