### PR TITLE
Create  AnandThakur2001.html

### PR DESCRIPTION
**Pull request by AnandThakur2001**

### CODE REVIEW

**Review by isyneha — COMMENTED** [review]
Seems like you didn't make changes to the index template. Please update your details before it can be merged.

**Review by isyneha — CHANGES_REQUESTED** [review]
Kindly update your details in Your Portfolio HTML File.

**Comment by AnandThakur2001** [comment]
already done ...
kindly look at it again
and accept the changes requested . Thankyou

**Review by isyneha — APPROVED** [review]
It is good now, Approving it. Thanks for your valuable contribution.

**Pull request merged**
