### PR TITLE
Footer Desgined for template website

### PR DESCRIPTION
**Pull request by sid172014**

### CODE REVIEW

**Comment by sid172014** [comment]
Hey @aastha-chauhan-gits i had some issues while syncing the pull request before this so i had to create a new pull request , im sorry , can you please check this now?

**Comment by sid172014** [comment]
I had to refork the whole project again , im sorry for that

**Comment by sid172014** [comment]
Screenshot 2022-10-10 at 5 01 31 PM

**Review by aastha-chauhan-gits — APPROVED** [review]
Looks Good to me now. Approving from my side.

**Pull request merged**
